version: '3'
services:
  projeto_ead_admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto_ead_admin
    ports:
      - "3001:8080"
    volumes:
      - .:/app
    restart: always
